# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

version: '3'
services:
  api:
    container_name: 'kernelci-api'
    build:
      context: api
    volumes:
      - '../api:/home/kernelci/api'
    ports:
      - '8001:8000'
  db:
    container_name: 'kernelci-db'
    image: 'mongo:5.0'
    volumes:
      - './db/data:/data/db'
